// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240401142851_fila")]
    partial class fila
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.MetaDados.Agente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FilaVirtualId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ObservacoesVirtualId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("id");

                    b.HasIndex("FilaVirtualId");

                    b.HasIndex("ObservacoesVirtualId");

                    b.ToTable("Agentes", (string)null);
                });

            modelBuilder.Entity("Model.MetaDados.Fila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Setor")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("Fila", (string)null);
                });

            modelBuilder.Entity("Model.MetaDados.ObservacoesAgente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Duracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HoraFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HoraInicial")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("Observacoes", (string)null);
                });

            modelBuilder.Entity("Model.MetaDados.Agente", b =>
                {
                    b.HasOne("Model.MetaDados.Fila", "FilaVirtual")
                        .WithMany()
                        .HasForeignKey("FilaVirtualId");

                    b.HasOne("Model.MetaDados.ObservacoesAgente", "ObservacoesVirtual")
                        .WithMany()
                        .HasForeignKey("ObservacoesVirtualId");

                    b.Navigation("FilaVirtual");

                    b.Navigation("ObservacoesVirtual");
                });
#pragma warning restore 612, 618
        }
    }
}
